package io.izzel.arclight.common.mod.util;

import net.minecraft.network.chat.Component;

import java.util.Iterator;
import java.util.stream.Stream;

/**
 * Spigot patches {@code Component} to implement {@code Iterable<Component>}; CraftBukkit code such as
 * {@code CraftChatMessage#fromComponent} relies on it. Forge ships the vanilla interface, so Arclight has
 * to add that method itself.
 *
 * <p>It used to be an interface mixin, but a mixin cannot win the race against mods whose
 * {@code IMixinConfigPlugin} loads {@code Component} while Mixin is still instantiating configs — that
 * happens a whole pass before any config is prepared. The method is now grafted on by
 * {@code ComponentIterableImplementer}, a ModLauncher launch plugin that runs on every class load,
 * and this class holds the actual logic so the generated bytecode stays trivial.
 */
public final class ComponentIterables {

    private ComponentIterables() {
    }

    public static Stream<Component> stream(Component self) {
        return Stream.concat(Stream.of(self), self.getSiblings().stream().flatMap(ComponentIterables::stream));
    }

    public static Iterator<Component> iterator(Component self) {
        return stream(self).iterator();
    }
}
